---
deployment:
  tasks:
    - export DEPLOYPATH=/home/khardl5/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - php $DEPLOYPATHbackend/artisan migrate:fresh --seed
    - php $DEPLOYPATHbackend/artisan create:tenant
