---
deployment:
  tasks:
    - export DEPLOYPATH=/home/khardl5/public_html/
    - export DEPLOYPATH=/home/khardl4test/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - ./home/khardl5/public_html/deploy.sh
    - ./home/khardl4test/public_html/deploy.sh
