version: '3'

# khardl
services:
    khardl_db:
#        platform: 'linux/amd64'
        container_name: khardl_db
        command: --max_allowed_packet=32505856
        image: mariadb
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./docker/database/data:/var/lib/mysql:z
            - ./docker/database/init:/docker-entrypoint-initdb.d

volumes:
  db:
    driver: local
