import React, { useEffect, useState } from "react";
import Herosection from "./components/Herosection";
import ProductSection from "./components/ProductSection";
import FooterRestuarant from "./components/Footer";
import AxiosInstance from "../../axios/axios";
import { useDispatch, useSelector } from "react-redux";
import { changeRestuarantEditorStyle } from "../../redux/NewEditor/restuarantEditorSlice";
import {
  getCartItemsCount,
  selectedCategoryAPI,
  setCategoriesAPI,
} from "../../redux/NewEditor/categoryAPISlice";
import { Helmet } from "react-helmet";
import { useTranslation } from "react-i18next";

const DummyData = {
  data: [
    {
        "id": 1,
        "name": "التصنيف الأول",
        "photo": "/img/category-icon.png",
        "created_at": "2024-01-15 13:16:43",
        "updated_at": "2024-01-15 13:16:43",
        "branch": {
            "id": 1,
            "name": "Branch 1",
            "phone": "966123456789",
            "address": "Riyadh",
            "lat": "37.70000000",
            "lng": "37.70000000",
            "monday_open": "15:16:00",
            "monday_close": "16:16:00",
            "monday_closed": 0,
            "tuesday_open": "16:16:00",
            "tuesday_close": "17:16:00",
            "tuesday_closed": 0,
            "wednesday_open": "17:16:00",
            "wednesday_close": "18:16:00",
            "wednesday_closed": 0,
            "thursday_open": "18:16:00",
            "thursday_close": "19:16:00",
            "thursday_closed": 0,
            "friday_open": "19:16:00",
            "friday_close": "20:16:00",
            "friday_closed": 0,
            "saturday_open": "13:16:00",
            "saturday_close": "14:16:00",
            "saturday_closed": 0,
            "sunday_open": "14:16:00",
            "sunday_close": "15:16:00",
            "sunday_closed": 0,
            "is_primary": 1,
            "delivery_availability": 0,
            "pickup_availability": 0,
            "preparation_time_delivery": "00:30:00",
            "created_at": "2024-01-15T10:16:43.000000Z",
            "updated_at": "2024-01-15T10:16:43.000000Z"
        },
        "user": {
            "id": 4,
            "first_name": "Worker",
            "last_name": "Worker",
            "email": "worker@first.com",
            "phone": "966000000000",
            "phone_verified_at": "2024-01-15T10:16:43.000000Z",
            "status": "active",
            "last_login": null,
            "msegat_id_verification": null,
            "address": "test address",
            "tap_verified": 0,
            "tap_customer_id": "cus_TS03A3920231337Jw212412549",
            "lat": "24.71360000",
            "lng": "46.67530000",
            "branch_id": 1,
            "created_at": "2024-01-15T10:16:43.000000Z",
            "updated_at": "2024-01-15T10:16:43.000000Z"
        },
        "items": [
            {
                "id": 1,
                "photo": "/tenancy/assets/seeders/items/1.jpg",
                "price": "471.00",
                "calories": 392,
                "name": "Item 1",
                "description": "Description 1",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 2,
                "photo": "/tenancy/assets/seeders/items/2.jpg",
                "price": "425.00",
                "calories": 63,
                "name": "Item 2",
                "description": "Description 2",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 3,
                "photo": "/tenancy/assets/seeders/items/3.jpg",
                "price": "378.00",
                "calories": 211,
                "name": "Item 3",
                "description": "Description 3",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 4,
                "photo": "/tenancy/assets/seeders/items/4.jpg",
                "price": "399.00",
                "calories": 89,
                "name": "Item 4",
                "description": "Description 4",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 5,
                "photo": "/tenancy/assets/seeders/items/5.jpg",
                "price": "451.00",
                "calories": 299,
                "name": "Item 5",
                "description": "Description 5",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 6,
                "photo": "/tenancy/assets/seeders/items/6.webp",
                "price": "38.00",
                "calories": 121,
                "name": "Item 6",
                "description": "Description 6",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 7,
                "photo": "/tenancy/assets/seeders/items/7.jpg",
                "price": "231.00",
                "calories": 117,
                "name": "Item 7",
                "description": "Description 7",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 8,
                "photo": "/tenancy/assets/seeders/items/8.jpg",
                "price": "148.00",
                "calories": 146,
                "name": "Item 8",
                "description": "Description 8",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 9,
                "photo": "/tenancy/assets/seeders/items/9.jpg",
                "price": "282.00",
                "calories": 161,
                "name": "Item 9",
                "description": "Description 9",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 10,
                "photo": "/tenancy/assets/seeders/items/10.jpg",
                "price": "272.00",
                "calories": 304,
                "name": "Item 10",
                "description": "Description 10",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            }
        ]
    },
    {
        "id": 2,
        "name": "التصنيف الثاني",
        "photo": "/img/category-icon.png",
        "created_at": "2024-01-15 13:16:43",
        "updated_at": "2024-01-15 13:16:43",
        "branch": {
            "id": 1,
            "name": "Branch 1",
            "phone": "966123456789",
            "address": "Riyadh",
            "lat": "37.70000000",
            "lng": "37.70000000",
            "monday_open": "15:16:00",
            "monday_close": "16:16:00",
            "monday_closed": 0,
            "tuesday_open": "16:16:00",
            "tuesday_close": "17:16:00",
            "tuesday_closed": 0,
            "wednesday_open": "17:16:00",
            "wednesday_close": "18:16:00",
            "wednesday_closed": 0,
            "thursday_open": "18:16:00",
            "thursday_close": "19:16:00",
            "thursday_closed": 0,
            "friday_open": "19:16:00",
            "friday_close": "20:16:00",
            "friday_closed": 0,
            "saturday_open": "13:16:00",
            "saturday_close": "14:16:00",
            "saturday_closed": 0,
            "sunday_open": "14:16:00",
            "sunday_close": "15:16:00",
            "sunday_closed": 0,
            "is_primary": 1,
            "delivery_availability": 0,
            "pickup_availability": 0,
            "preparation_time_delivery": "00:30:00",
            "created_at": "2024-01-15T10:16:43.000000Z",
            "updated_at": "2024-01-15T10:16:43.000000Z"
        },
        "user": {
            "id": 4,
            "first_name": "Worker",
            "last_name": "Worker",
            "email": "worker@first.com",
            "phone": "966000000000",
            "phone_verified_at": "2024-01-15T10:16:43.000000Z",
            "status": "active",
            "last_login": null,
            "msegat_id_verification": null,
            "address": "test address",
            "tap_verified": 0,
            "tap_customer_id": "cus_TS03A3920231337Jw212412549",
            "lat": "24.71360000",
            "lng": "46.67530000",
            "branch_id": 1,
            "created_at": "2024-01-15T10:16:43.000000Z",
            "updated_at": "2024-01-15T10:16:43.000000Z"
        },
        "items": [
            {
                "id": 11,
                "photo": "/tenancy/assets/seeders/items/1.jpg",
                "price": "144.00",
                "calories": 75,
                "name": "Item 1",
                "description": "Description 1",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 12,
                "photo": "/tenancy/assets/seeders/items/2.jpg",
                "price": "307.00",
                "calories": 422,
                "name": "Item 2",
                "description": "Description 2",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 13,
                "photo": "/tenancy/assets/seeders/items/3.jpg",
                "price": "173.00",
                "calories": 357,
                "name": "Item 3",
                "description": "Description 3",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 14,
                "photo": "/tenancy/assets/seeders/items/4.jpg",
                "price": "250.00",
                "calories": 375,
                "name": "Item 4",
                "description": "Description 4",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 15,
                "photo": "/tenancy/assets/seeders/items/5.jpg",
                "price": "303.00",
                "calories": 128,
                "name": "Item 5",
                "description": "Description 5",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 16,
                "photo": "/tenancy/assets/seeders/items/6.webp",
                "price": "61.00",
                "calories": 23,
                "name": "Item 6",
                "description": "Description 6",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 17,
                "photo": "/tenancy/assets/seeders/items/7.jpg",
                "price": "40.00",
                "calories": 248,
                "name": "Item 7",
                "description": "Description 7",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 18,
                "photo": "/tenancy/assets/seeders/items/8.jpg",
                "price": "308.00",
                "calories": 393,
                "name": "Item 8",
                "description": "Description 8",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 19,
                "photo": "/tenancy/assets/seeders/items/9.jpg",
                "price": "70.00",
                "calories": 317,
                "name": "Item 9",
                "description": "Description 9",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 20,
                "photo": "/tenancy/assets/seeders/items/10.jpg",
                "price": "355.00",
                "calories": 459,
                "name": "Item 10",
                "description": "Description 10",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            }
        ]
    },
    {
        "id": 3,
        "name": "التصنيف الأول",
        "photo": "/img/category-icon.png",
        "created_at": "2024-01-15 13:16:43",
        "updated_at": "2024-01-15 13:16:43",
        "branch": {
            "id": 1,
            "name": "Branch 1",
            "phone": "966123456789",
            "address": "Riyadh",
            "lat": "37.70000000",
            "lng": "37.70000000",
            "monday_open": "15:16:00",
            "monday_close": "16:16:00",
            "monday_closed": 0,
            "tuesday_open": "16:16:00",
            "tuesday_close": "17:16:00",
            "tuesday_closed": 0,
            "wednesday_open": "17:16:00",
            "wednesday_close": "18:16:00",
            "wednesday_closed": 0,
            "thursday_open": "18:16:00",
            "thursday_close": "19:16:00",
            "thursday_closed": 0,
            "friday_open": "19:16:00",
            "friday_close": "20:16:00",
            "friday_closed": 0,
            "saturday_open": "13:16:00",
            "saturday_close": "14:16:00",
            "saturday_closed": 0,
            "sunday_open": "14:16:00",
            "sunday_close": "15:16:00",
            "sunday_closed": 0,
            "is_primary": 1,
            "delivery_availability": 0,
            "pickup_availability": 0,
            "preparation_time_delivery": "00:30:00",
            "created_at": "2024-01-15T10:16:43.000000Z",
            "updated_at": "2024-01-15T10:16:43.000000Z"
        },
        "user": {
            "id": 4,
            "first_name": "Worker",
            "last_name": "Worker",
            "email": "worker@first.com",
            "phone": "966000000000",
            "phone_verified_at": "2024-01-15T10:16:43.000000Z",
            "status": "active",
            "last_login": null,
            "msegat_id_verification": null,
            "address": "test address",
            "tap_verified": 0,
            "tap_customer_id": "cus_TS03A3920231337Jw212412549",
            "lat": "24.71360000",
            "lng": "46.67530000",
            "branch_id": 1,
            "created_at": "2024-01-15T10:16:43.000000Z",
            "updated_at": "2024-01-15T10:16:43.000000Z"
        },
        "items": [
            {
                "id": 21,
                "photo": "/tenancy/assets/seeders/items/1.jpg",
                "price": "492.00",
                "calories": 377,
                "name": "Item 1",
                "description": "Description 1",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 22,
                "photo": "/tenancy/assets/seeders/items/2.jpg",
                "price": "135.00",
                "calories": 58,
                "name": "Item 2",
                "description": "Description 2",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 23,
                "photo": "/tenancy/assets/seeders/items/3.jpg",
                "price": "265.00",
                "calories": 201,
                "name": "Item 3",
                "description": "Description 3",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 24,
                "photo": "/tenancy/assets/seeders/items/4.jpg",
                "price": "10.00",
                "calories": 58,
                "name": "Item 4",
                "description": "Description 4",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 25,
                "photo": "/tenancy/assets/seeders/items/5.jpg",
                "price": "237.00",
                "calories": 177,
                "name": "Item 5",
                "description": "Description 5",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 26,
                "photo": "/tenancy/assets/seeders/items/6.webp",
                "price": "33.00",
                "calories": 219,
                "name": "Item 6",
                "description": "Description 6",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 27,
                "photo": "/tenancy/assets/seeders/items/7.jpg",
                "price": "457.00",
                "calories": 341,
                "name": "Item 7",
                "description": "Description 7",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 28,
                "photo": "/tenancy/assets/seeders/items/8.jpg",
                "price": "160.00",
                "calories": 149,
                "name": "Item 8",
                "description": "Description 8",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 29,
                "photo": "/tenancy/assets/seeders/items/9.jpg",
                "price": "161.00",
                "calories": 161,
                "name": "Item 9",
                "description": "Description 9",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 30,
                "photo": "/tenancy/assets/seeders/items/10.jpg",
                "price": "306.00",
                "calories": 404,
                "name": "Item 10",
                "description": "Description 10",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            }
        ]
    },
    {
        "id": 4,
        "name": "التصنيف الثاني",
        "photo": "/img/category-icon.png",
        "created_at": "2024-01-15 13:16:43",
        "updated_at": "2024-01-15 13:16:43",
        "branch": {
            "id": 1,
            "name": "Branch 1",
            "phone": "966123456789",
            "address": "Riyadh",
            "lat": "37.70000000",
            "lng": "37.70000000",
            "monday_open": "15:16:00",
            "monday_close": "16:16:00",
            "monday_closed": 0,
            "tuesday_open": "16:16:00",
            "tuesday_close": "17:16:00",
            "tuesday_closed": 0,
            "wednesday_open": "17:16:00",
            "wednesday_close": "18:16:00",
            "wednesday_closed": 0,
            "thursday_open": "18:16:00",
            "thursday_close": "19:16:00",
            "thursday_closed": 0,
            "friday_open": "19:16:00",
            "friday_close": "20:16:00",
            "friday_closed": 0,
            "saturday_open": "13:16:00",
            "saturday_close": "14:16:00",
            "saturday_closed": 0,
            "sunday_open": "14:16:00",
            "sunday_close": "15:16:00",
            "sunday_closed": 0,
            "is_primary": 1,
            "delivery_availability": 0,
            "pickup_availability": 0,
            "preparation_time_delivery": "00:30:00",
            "created_at": "2024-01-15T10:16:43.000000Z",
            "updated_at": "2024-01-15T10:16:43.000000Z"
        },
        "user": {
            "id": 4,
            "first_name": "Worker",
            "last_name": "Worker",
            "email": "worker@first.com",
            "phone": "966000000000",
            "phone_verified_at": "2024-01-15T10:16:43.000000Z",
            "status": "active",
            "last_login": null,
            "msegat_id_verification": null,
            "address": "test address",
            "tap_verified": 0,
            "tap_customer_id": "cus_TS03A3920231337Jw212412549",
            "lat": "24.71360000",
            "lng": "46.67530000",
            "branch_id": 1,
            "created_at": "2024-01-15T10:16:43.000000Z",
            "updated_at": "2024-01-15T10:16:43.000000Z"
        },
        "items": [
            {
                "id": 31,
                "photo": "/tenancy/assets/seeders/items/1.jpg",
                "price": "338.00",
                "calories": 345,
                "name": "Item 1",
                "description": "Description 1",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 32,
                "photo": "/tenancy/assets/seeders/items/2.jpg",
                "price": "207.00",
                "calories": 232,
                "name": "Item 2",
                "description": "Description 2",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 33,
                "photo": "/tenancy/assets/seeders/items/3.jpg",
                "price": "229.00",
                "calories": 376,
                "name": "Item 3",
                "description": "Description 3",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 34,
                "photo": "/tenancy/assets/seeders/items/4.jpg",
                "price": "157.00",
                "calories": 70,
                "name": "Item 4",
                "description": "Description 4",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 35,
                "photo": "/tenancy/assets/seeders/items/5.jpg",
                "price": "440.00",
                "calories": 173,
                "name": "Item 5",
                "description": "Description 5",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 36,
                "photo": "/tenancy/assets/seeders/items/6.webp",
                "price": "13.00",
                "calories": 99,
                "name": "Item 6",
                "description": "Description 6",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 37,
                "photo": "/tenancy/assets/seeders/items/7.jpg",
                "price": "280.00",
                "calories": 202,
                "name": "Item 7",
                "description": "Description 7",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 38,
                "photo": "/tenancy/assets/seeders/items/8.jpg",
                "price": "438.00",
                "calories": 319,
                "name": "Item 8",
                "description": "Description 8",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 39,
                "photo": "/tenancy/assets/seeders/items/9.jpg",
                "price": "322.00",
                "calories": 218,
                "name": "Item 9",
                "description": "Description 9",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 40,
                "photo": "/tenancy/assets/seeders/items/10.jpg",
                "price": "355.00",
                "calories": 486,
                "name": "Item 10",
                "description": "Description 10",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            }
        ]
    },
    {
        "id": 5,
        "name": "التصنيف الأول",
        "photo": "/img/category-icon.png",
        "created_at": "2024-01-15 13:16:43",
        "updated_at": "2024-01-15 13:16:43",
        "branch": {
            "id": 1,
            "name": "Branch 1",
            "phone": "966123456789",
            "address": "Riyadh",
            "lat": "37.70000000",
            "lng": "37.70000000",
            "monday_open": "15:16:00",
            "monday_close": "16:16:00",
            "monday_closed": 0,
            "tuesday_open": "16:16:00",
            "tuesday_close": "17:16:00",
            "tuesday_closed": 0,
            "wednesday_open": "17:16:00",
            "wednesday_close": "18:16:00",
            "wednesday_closed": 0,
            "thursday_open": "18:16:00",
            "thursday_close": "19:16:00",
            "thursday_closed": 0,
            "friday_open": "19:16:00",
            "friday_close": "20:16:00",
            "friday_closed": 0,
            "saturday_open": "13:16:00",
            "saturday_close": "14:16:00",
            "saturday_closed": 0,
            "sunday_open": "14:16:00",
            "sunday_close": "15:16:00",
            "sunday_closed": 0,
            "is_primary": 1,
            "delivery_availability": 0,
            "pickup_availability": 0,
            "preparation_time_delivery": "00:30:00",
            "created_at": "2024-01-15T10:16:43.000000Z",
            "updated_at": "2024-01-15T10:16:43.000000Z"
        },
        "user": {
            "id": 4,
            "first_name": "Worker",
            "last_name": "Worker",
            "email": "worker@first.com",
            "phone": "966000000000",
            "phone_verified_at": "2024-01-15T10:16:43.000000Z",
            "status": "active",
            "last_login": null,
            "msegat_id_verification": null,
            "address": "test address",
            "tap_verified": 0,
            "tap_customer_id": "cus_TS03A3920231337Jw212412549",
            "lat": "24.71360000",
            "lng": "46.67530000",
            "branch_id": 1,
            "created_at": "2024-01-15T10:16:43.000000Z",
            "updated_at": "2024-01-15T10:16:43.000000Z"
        },
        "items": [
            {
                "id": 41,
                "photo": "/tenancy/assets/seeders/items/1.jpg",
                "price": "379.00",
                "calories": 164,
                "name": "Item 1",
                "description": "Description 1",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 42,
                "photo": "/tenancy/assets/seeders/items/2.jpg",
                "price": "403.00",
                "calories": 69,
                "name": "Item 2",
                "description": "Description 2",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 43,
                "photo": "/tenancy/assets/seeders/items/3.jpg",
                "price": "300.00",
                "calories": 406,
                "name": "Item 3",
                "description": "Description 3",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 44,
                "photo": "/tenancy/assets/seeders/items/4.jpg",
                "price": "474.00",
                "calories": 409,
                "name": "Item 4",
                "description": "Description 4",
                "availability": 0,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 45,
                "photo": "/tenancy/assets/seeders/items/5.jpg",
                "price": "365.00",
                "calories": 180,
                "name": "Item 5",
                "description": "Description 5",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 46,
                "photo": "/tenancy/assets/seeders/items/6.webp",
                "price": "220.00",
                "calories": 131,
                "name": "Item 6",
                "description": "Description 6",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 47,
                "photo": "/tenancy/assets/seeders/items/7.jpg",
                "price": "178.00",
                "calories": 50,
                "name": "Item 7",
                "description": "Description 7",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 48,
                "photo": "/tenancy/assets/seeders/items/8.jpg",
                "price": "446.00",
                "calories": 454,
                "name": "Item 8",
                "description": "Description 8",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 49,
                "photo": "/tenancy/assets/seeders/items/9.jpg",
                "price": "209.00",
                "calories": 303,
                "name": "Item 9",
                "description": "Description 9",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            },
            {
                "id": 50,
                "photo": "https://first.khardl.com/tenancy/assets/seeders/items/10.jpg",
                "price": "107.00",
                "calories": 460,
                "name": "Item 10",
                "description": "Description 10",
                "availability": 1,
                "checkbox_required": null,
                "checkbox_input_titles": null,
                "checkbox_input_maximum_choices": null,
                "checkbox_input_names": null,
                "checkbox_input_prices": null,
                "selection_required": null,
                "selection_input_names": null,
                "selection_input_prices": null,
                "selection_input_titles": null,
                "dropdown_required": null,
                "dropdown_input_names": null,
                "dropdown_input_titles": null
            }
        ]
    }
],
};

export const RestuarantHomePage = () => {
  const dispatch = useDispatch();
  const { t } = useTranslation();
  const [isMobile, setIsMobile] = useState(false);
  const [isLoading, setisLoading] = useState(true);
  const categories = useSelector((state) => state.categoryAPI.categories);
  const [dummyData, setDummyData] = useState(DummyData.data);

  const restaurantStyle = useSelector((state) => state.restuarantEditorStyle);

  let branch_id = localStorage.getItem("selected_branch_id");
  // let branch_id = 2

  const fetchCategoriesData = async () => {
    try {
      const restaurantCategoriesResponse = await AxiosInstance.get(
        `categories?items&user&branch${
          branch_id ? `&selected_branch_id=${branch_id}` : ""
        }`
      );
      // const restaurantCategoriesResponse =[];

      if (restaurantCategoriesResponse.data && restaurantCategoriesResponse.data?.data && restaurantCategoriesResponse.data?.data.length > 1) {
        dispatch(setCategoriesAPI(restaurantCategoriesResponse.data?.data));
        dispatch(
          selectedCategoryAPI({
            name: restaurantCategoriesResponse.data?.data[0].name,
            id: restaurantCategoriesResponse.data?.data[0].id,
          })
        );
        setisLoading(false);
        console.log(">> branch_id >>", branch_id);

        if (!branch_id) {
          branch_id = restaurantCategoriesResponse.data?.data[0]?.branch?.id;
          localStorage.setItem("selected_branch_id", branch_id);
        }
      } else {
        dispatch(setCategoriesAPI(dummyData));
      }
    } catch (error) {
      // toast.error(`${t('Failed to send verification code')}`)
      console.log(error);
      setisLoading(false);
    }
  };
  const fetchResStyleData = async () => {
    try {
      AxiosInstance.get(`restaurant-style`).then((response) => {
        console.log("DATA", response.data?.data);
        dispatch(changeRestuarantEditorStyle(response.data?.data));
      });
      setisLoading(false);
    } catch (error) {
      // toast.error(`${t('Failed to send verification code')}`)
      console.log(error);
      setisLoading(false);
    }
  };
  useEffect(() => {
    const isMobile = /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);

    setIsMobile(isMobile);
  }, []);

  const fetchCartData = async () => {
    try {
      const cartResponse = await AxiosInstance.get(`carts`);
      if (cartResponse.data) {
        dispatch(getCartItemsCount(cartResponse.data?.data?.items?.length));
      }
    } catch (error) {
      // toast.error(`${t('Failed to send verification code')}`)
      console.log(error);
    }
  };

  useEffect(() => {
    fetchCategoriesData().then(() => {
      console.log("fetched restuarant style successfully");
    });

    fetchResStyleData();
    fetchCartData().then(() => {
      console.log("fetched cart item count successfully");
    });
  }, []);

  console.log("isLoading", isLoading);

  if (isLoading || !restaurantStyle) {
    return (
      <div className="w-screen h-screen flex items-center justify-center">
        <span className="loading loading-spinner text-primary"></span>
      </div>
    );
  }

  return (
    <>
      {/* <Helmet>
        <title>{t("Home")}</title>
        <link
          rel="icon"
          type="image/png"
          href={restaurantStyle.logo}
          sizes="16x16"
        />
      </Helmet> */}

      <div
        style={{
          backgroundColor: restaurantStyle?.page_color,
          fontFamily: restaurantStyle.text_fontFamily,
        }}
      >
        <Herosection isMobile={isMobile} categories={categories || dummyData} />
        <ProductSection
          categories={categories || dummyData}
          isMobile={isMobile}
        />
        <FooterRestuarant />
      </div>
    </>
  );
};
