name: Laravel

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: |
        pwd
        ls
        php -r "file_exists('backend/.env') || copy('backend/.env.example', 'backend/.env');"

    - name: Install Dependencies
      run: |
        cd backend
        composer install
    - name: Generate key
      run: |
        php backend/artisan key:generate
    - name: Directory Permissions
      run: |
        chmod -R 777 storage backend/bootstrap/cache
    - name: Create Database
      run: |
        pwd
        ls
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        pwd
        ls
        backend/vendor/bin/phpunit
