name: Laravel

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: |
        pwd
        ls
        php -r "file_exists('backend/.env') || copy('backend/.env.example', 'backend/.env');"

    - name: Install Dependencies
      run: |
        cd backend
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: |
        php backend/artisan key:generate
    - name: Directory Permissions
      run: |
        mkdir -p backend/bootstrap/cache
        chmod -R 777 backend/storage backend/bootstrap/cache
#    - name: Create Database
#      run: |
#        pwd
#        ls
#        mkdir -p backend/database
#        touch backend/database/database.sqlite
#    - name: Execute tests (Unit and Feature tests) via PHPUnit
#      env:
#        DB_CONNECTION: sqlite
#        DB_DATABASE: backend/database/database.sqlite
#      run: |
#        pwd
#        ls
#        backend/vendor/bin/phpunit backend/tests
  deploy:
    runs-on: [self-hosted]
    steps:
    - name: Deploy
      run: |
        pwd
        ls
        /home/khardl5/public_html/testing-deploy.sh